export enum InMemoryProfileMetadataError {
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_STATE_MALFORMED = "PROFILE_STATE_MALFORMED",
  MISSING_VALUE = "MISSING_VALUE",
  PROFILE_OUTDATED = "PROFILE_OUTDATED",
}
