export enum InMemorySessionError {
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_OUTDATED = "SESSION_OUTDATED",
  SESSION_MALFORMED = "SESSION_MALFORMED",
  SESSION_ALREADY_STARTED = "SESSION_ALREADY_STARTED",
}
