export enum InMemorySessionMetadataError {
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_OUTDATED = "SESSION_OUTDATED",
  SESSION_STATE_MALFORMED = "SESSION_STATE_MALFORMED",
  SESSION_ALREADY_STARTED = "SESSION_ALREADY_STARTED",
}
