export enum SlotStatus {
  SCHEDULED = "SCHEDULED",
  RESCHEDULED = "RESCHEDULED",
  CANCELLED = "CANCELLED",
  WAITING = "WAITING",
  ONGOING = "ONGOING",
  NOT_ENOUGH_PLAYERS = "NOT_ENOUGH_PLAYERS",
  COMPLETED = "COMPLETED",
}
